### ISSUE TITLE
Improve english hyphenation

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#154] opened 2017-12-01 09:11 UTC
Job 1766 gets hyphenation like this
t-hemes
fis-herman
t-hat

**Comment by bertfrees** [comment] 2017-12-01 11:22
Is this with Norwegian (force-norwegian) or English braille rules?

**Comment by KariRudjord** [comment] 2017-12-01 11:35
The whole book is marked xml lang en so I think english braille rules

**Comment by bertfrees** [comment] 2017-12-01 11:36
The "force-norwegian" option is important here.

**Comment by KariRudjord** [comment] 2017-12-01 11:40
I thought that if the whole book is marked en it would be turned off? Maybe I'm wrong? OK, its written in the GUI, it always use norwegin, yes.

**Comment by bertfrees** [comment] 2017-12-01 11:47
That's not the case at the moment. So this issue is probably a duplicate of https://github.com/nlbdev/pipeline/issues/152.

**Comment by matskober** [comment] 2017-12-01 12:33
I ran an English book here the other day, unchecking "alltid Norsk", but
the t-hat was present there as well ...

**Comment by josteinaj** [comment] 2017-12-04 09:54
Closing as duplicate of #152.

**Closed as completed by josteinaj** 2017-12-04 09:54 UTC
Labels: duplicate, Priority:1 - Low

**Comment by bertfrees** [comment] 2017-12-04 11:18
But what about what Mats said?

**Comment by josteinaj** [comment] 2017-12-04 14:02
Oh, I see. Hyphenation also happens for english books even if force-norwegian is false?
