### ISSUE TITLE
Margin when print page numbers are left out

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#79] opened 2017-07-03 08:19 UTC
When print page numbers is left out of a production, the margin shall still be 2 columns. Now it is 1 according to Jostein.

**Comment by bertfrees** [comment] 2017-07-03 10:28
Can I get an example file please?

**Comment by josteinaj** [comment] 2017-07-03 10:30
I'll create a test.

**Comment by josteinaj** [comment] 2017-07-03 10:45
I can't reproduce it. I don't know why I saw it earlier. But I'll commit a test for it anyway.

**Comment by KariRudjord** [comment] 2017-07-03 14:17
When I try, there are 2 columns in the margin, and I can't remember I've seen anything else when I have tested, @josteinaj

**Comment by josteinaj** [comment] 2017-07-03 14:43
I'm closing this issue then. Maybe it was just in my imagination :)

**Closed as completed by josteinaj** 2017-07-03 14:43 UTC
