### ISSUE TITLE
Returning issue: Page number vs sheets in "Om boka"

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#164] opened 2017-12-19 13:04 UTC
See also issue #123 - regarding page counting when "singel sided" embossing (e.g. not duplex) 

Jobs #1974 and #1976: I thought we had fixed this, but now it is showing sheets again and not pages in "Om boka". 

@josteinaj asked "how many pages are there in a one-sided book? do we count the backside of each page as a page? I suppose not?"

I assume the info in "Om boka" is targeted at the reader, and not the library or the embossing house. So the number of pages in "Om boka" should be the same the number as the one found on the last paginated page in the braille book.

**Comment by josteinaj** [comment] 2018-01-02 14:02
The number of pages on the about page is currently the number of sheets divided by two regardless of whether the PEF is duplex or not. @matskober is this a duplicate of #123?

**Comment by matskober** [comment] 2018-01-03 09:27
Yeah, it seems so

**Comment by josteinaj** [comment] 2018-01-03 10:10
Ok, I'm closing it then.

**Closed as completed by josteinaj** 2018-01-03 10:10 UTC
