### ISSUE TITLE
Retest hard page breaks and orphan/widow control (sprint 4)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#29] opened 2017-06-27 10:54 UTC

**Comment by matskober** [comment] 2017-11-29 10:33
Orphan/widow control seems to work as intended!
![image](https://user-images.githubusercontent.com/8014898/33370842-ac2ffee4-d4f0-11e7-9602-fe2801bce518.png)

**Comment by matskober** [comment] 2017-11-29 11:04
The 'hard page breaks' referred to in  #29 - is that connected to the orphan/widow issue, or is it 'page-breake-before'-matter?

**Comment by josteinaj** [comment] 2017-11-29 13:06
Not sure. `page-break-before` should already work, so I suppose the issue to test is "orphan/widow control", but I don't know what kind of "control" this refers to. @KariRudjord do you remember?

**Comment by KariRudjord** [comment] 2017-11-29 13:12
It seems from Mats' example above that orphan/widow is working like intended, so i close the issue.

**Closed as completed by KariRudjord** 2017-11-29 13:12 UTC
Labels: Priority:2 - Medium
